version: '3.4'
services:
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: mssql
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      SA_PASSWORD: "SqlPocketNurse"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
  pocketnurse:
    build: PocketNurse
    image: pocketnurse
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"    
    depends_on:
      - mssql
    container_name: pocketnurse
    ports:
      - "80:80"
volumes:
  sqlvolume:
